### ISSUE TITLE
Add two badges, one showing open pull requests and second showing closed pull requests of this repo

### ISSUE THREAD

**Issue by ows-ali** [ows-ali/Hacktoberfest#11]
Please see README.md and visit https://shields.io to see how to add a badge.
Don't forget to add your name in Contributors in README.md

**Comment by saiij** [comment]
I'm on it! :+1:

**Comment by ows-ali** [comment]
Maybe because you are using the different repository path. For example, if it is cdnjs/cdnjs then it should be ows-ali/Hacktoberfest to point to this repository.
