### ISSUE TITLE
Fix readme issue where an username was placed instead of a country name

### ISSUE THREAD

**Issue by Kurolox** [ows-ali/Hacktoberfest#17]
I'd fix the fact that `Kurolox` isn't a country yet, but due to time constraints and budget reasons I don't think I'll be able to make that one happen before hacktoberfest ends. Oh well.

**Comment by ows-ali** [comment]
Oh I wish I was able to make Hacktoberfest wait to see the `Kurolox` as a country 😐 but well it is not that lucky.
