### ISSUE TITLE
Add instructions in CONTRIBUTING.md for adding upstream remote 

### ISSUE THREAD

**Issue by ows-ali** [ows-ali/Hacktoberfest#22]
Add upstream instructions, so contributors can resolve more issues themselves when there fork is behind the repo's master or if there is any merge conflict.

**Comment by seancyw** [comment]
@ows-ali , 
I will grab this as well. Thanks.

**Comment by ows-ali** [comment]
Sure @seancyw, please add your name in Contributors list as well 😊

**Comment by seancyw** [comment]
@ows-ali ,
the changes is updated. Please check and merged the changes if no further comment. :)

**Comment by ows-ali** [comment]
@seancyw great work. And somewhat different from what I will do. Like for step 2 I will do git pull from upstream and then make any changes and git push origin master.
But both works.
Can you please make a small change? It is not necessary to use master branch in forked repo as you mentioned in Step 3, so can you add that they can use master or their own new branch?

**Comment by ows-ali** [comment]
Thanks for resolving the issue @seancyw
