### ISSUE TITLE
Number of PRs required for Hacktoberfest

### ISSUE THREAD

**Issue by metonymic-smokey** [ows-ali/Hacktoberfest#259]
###### Expected behavior and actual behavior
# Expected behaviour:
* The number of PRs required for Hacktoberfest 2019 is 4.

# Actual behavior:
* The README mentions it as 5.

###### Steps to reproduce the problem
* This is a minor documentation fix, involving changing 5 to 4 in the README.

**Comment by metonymic-smokey** [comment]
@ows-ali I've addressed a few other cosmetic errors in the REAME in #257 
What do you think about creating a separate branch for issues other than the main coding problems? Issues could be better organised that way.

**Comment by KAHund** [comment]
I didn't see this issue anywhere in the README, but I found and fixed it in CONTRIBUTING.md

**Comment by adityaoberai** [comment]
Issue was still there. I made the edit too.

**Comment by metonymic-smokey** [comment]
Thanks @KAHund and @adityaoberai!
